const ADD_INGREDIENT = "ADD_INGREDIENT";
const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
const RESET_INGREDIENTS = "RESET_INGREDIENTS";

export { ADD_INGREDIENT, RESET_INGREDIENTS, REMOVE_INGREDIENT };
